from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package='task2',
            executable='detect_faces',
            name='detect_faces',
            output='screen',
        ),
        Node(
            package='task2',
            executable='detect_rings',
            name='detect_rings',
            output='screen',
        ),
        Node(
            package='task2',
            executable='detect_anomalies',
            name='detect_anomalies',
            output='screen',
        ),
        Node(
            package='task2',
            executable='speak',
            name='speak',
            output='screen',
        ),
        Node(
            package='task2',
            executable='classify_face',
            name='classify_face',
            output='screen',
        ),
        Node(
            package='task2',
            executable='map_query',
            name='map_query',
            output='screen',
        ),
        Node(
            package='task2',
            executable='line_fit',
            name='line_fit',
            output='screen',
        ),
        Node(
            package='task2',
            executable='blue_line',
            name='blue_line',
            output='screen',
        ),
        Node(
            package='task2',
            executable='conversation',
            name='conversation',
            output='screen',
        ),
        Node(
            package='dis_tutorial7',
            executable='arm_mover_actions.py',
            name='arm_mover_actions',
            output='screen',
        ),
    ])
