detect_barrel_cpp:
  ros__parameters:
    image_topic: /oakd/rgb/preview/image_raw
    point_cloud_topic: /oakd/rgb/preview/depth/points
    target_frame: map

    barrel_topic: /barrel_detect
    marker_topic: /barrel_markers
    debug_overlay_topic: /barrel/debug_overlay

    publish_hz: 2.0
    sync_queue_size: 5
    sync_slop_s: 0.08
    first_track_id: 100
    accept_threshold: 4
    dedup_distance_m: 0.45
    republish_move_threshold_m: 0.05
    track_timeout_frames: 18
    max_barrel_height_m: 0.42

    depth_min_m: 0.15
    depth_max_m: 6.0
    cluster_tolerance_m: 0.07
    cluster_min_points: 40
    cluster_max_points: 20000
    normal_search_radius_m: 0.05
    ransac_max_iterations: 250
    ransac_distance_threshold_m: 0.035
    ransac_normal_distance_weight: 0.1
    cylinder_radius_min_m: 0.08
    cylinder_radius_max_m: 0.45

    cylinder_inlier_min: 25 #35

    cylinder_fit_residual_max_m: 0.08 #0.05

    horizontal_dot_threshold: 0.55

    use_color_prefilter: true
    candidate_min_area_px: 180.0
    candidate_max_area_px: 90000.0
    candidate_min_width_px: 12
    candidate_min_height_px: 12

    color_confidence_min: 0.25 #0.45

    mask_morph_open_kernel: 3

    mask_morph_close_kernel: 3 #9

    allow_gray_fallback_label: false
    gray_saturation_max: 35

    hsv_ranges.red: [0, 90, 40, 10, 255, 255, 160, 90, 40, 179, 255, 255]
    hsv_ranges.green: [35, 70, 35, 90, 255, 255]
    hsv_ranges.blue: [90, 60, 35, 140, 255, 255]
    hsv_ranges.yellow: [16, 80, 50, 35, 255, 255]
    hsv_ranges.purple: [130, 45, 35, 165, 255, 255]
    hsv_ranges.orange: [5, 80, 45, 20, 255, 255]
    hsv_ranges.brown: [5, 35, 20, 25, 190, 170]
    hsv_ranges.black: [0, 0, 0, 179, 255, 55]

    stability_window_m: 8
    stability_required_n: 5

    marker_scale_x: 0.28
    marker_scale_y: 0.28
    marker_scale_z: 0.45
    marker_alpha: 0.9
    marker_lifetime_s: 1.5
    marker_namespace: barrels

    enable_debug_overlay: true
    debug_window_name: barrel
    show_debug_window: false
    draw_barrel_outline: true
    draw_blob_metrics: true
    draw_track_ids: true
    draw_normal_arrow: true
